package battleshipeksamen;

import java.awt.*;
import javax.swing.JPanel;

public class NextPlayerPanel extends javax.swing.JPanel {

    Image NextPlayerPic = Toolkit.getDefaultToolkit().getImage("NextPlayerPic.jpg");
    CardLayout cardLayout;
    JPanel parentPanel;
    BattleshipGame spil;

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(NextPlayerPic, 0, 0, getWidth(), getHeight(), this);    // Tegner baggrundsbillede
    }

    public NextPlayerPanel(JPanel p) {
        initComponents();
        this.parentPanel = p;
        cardLayout = (CardLayout) parentPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextButton.setText("Next player");
        nextButton.setToolTipText("");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(575, 575, 575)
                .addComponent(nextButton)
                .addContainerGap(582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Skifter tur imellem spillere
 * @param evt 
 */
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (spil.p1.getPlayerTurn() == true) {
            spil.p1.setPlayerTurn(false);
            spil.p2.setPlayerTurn(true);
            if (spil.p2.getPlaceShips() == true) {
                spil.p2.setPlayerTurnUsed(true);
            } else {
                spil.p2.setPlayerTurnUsed(false);
            }
        } else {
            spil.p2.setPlayerTurn(false);
            spil.p1.setPlayerTurn(true);
            spil.p1.setPlayerTurnUsed(false);
        }
        cardLayout.show(parentPanel, "game");
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
