package battleshipeksamen;

import java.awt.*;
import javax.swing.JPanel;

public class WinnerPanel extends javax.swing.JPanel {
    
    Image win = Toolkit.getDefaultToolkit().getImage("win.jpg");
    BattleshipGame spil;
    CardLayout cardLayout;
    JPanel parentPanel;
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(win, 0, 0, getWidth(), getHeight(), this);
    }
    
    public WinnerPanel(JPanel p) {
        initComponents();
        this.parentPanel = p;
        cardLayout = (CardLayout) parentPanel.getLayout();
    }
    
    /**
     * Opdaterer label som viser stats
     */
    public void showStats() {
        
        p1Hit.setText("Hits: " + spil.p1.getShotHit());
        p1Shots.setText("Shots: " + spil.p1.getTotalShots());
        p1Miss.setText("Missed: " + spil.p1.getShotMissed());
        p1Acc.setText("Acc: " + spil.p1.getTotalAccuracy() + "%");
        
        p2Hit.setText("Hits: " + spil.p2.getShotHit());
        p2Shots.setText("Shots: " + spil.p2.getTotalShots());
        p2Miss.setText("Missed: " + spil.p2.getShotMissed());
        p2Acc.setText("Acc: " + spil.p2.getTotalAccuracy() + "%");
    }
    
    /**
     * Opdaterer label som viser vinder af spillet
     */
    public void showWinner() {
        if (spil.p1.totalHPRemaining() == 0) {
            labelWinner.setText("Player 2 WON");
        } else {
            labelWinner.setText("Player 1 WON");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        winnerIsLabel = new javax.swing.JLabel();
        labelWinner = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        p1Hit = new javax.swing.JLabel();
        p1Miss = new javax.swing.JLabel();
        p1Acc = new javax.swing.JLabel();
        p1Shots = new javax.swing.JLabel();
        p2Hit = new javax.swing.JLabel();
        p2Miss = new javax.swing.JLabel();
        p2Acc = new javax.swing.JLabel();
        p2Shots = new javax.swing.JLabel();
        buttonAfslut = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1280, 720));

        winnerIsLabel.setBackground(new java.awt.Color(255, 255, 255));
        winnerIsLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        winnerIsLabel.setForeground(new java.awt.Color(255, 51, 51));
        winnerIsLabel.setText("The winner is....");

        labelWinner.setBackground(new java.awt.Color(255, 255, 255));
        labelWinner.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelWinner.setForeground(new java.awt.Color(102, 102, 255));
        labelWinner.setText("Player");

        player1Label.setBackground(new java.awt.Color(255, 255, 255));
        player1Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        player1Label.setForeground(new java.awt.Color(255, 0, 51));
        player1Label.setText("Player 1");

        player2Label.setBackground(new java.awt.Color(255, 255, 255));
        player2Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        player2Label.setForeground(new java.awt.Color(255, 51, 51));
        player2Label.setText("Player 2");

        p1Hit.setBackground(new java.awt.Color(255, 255, 255));
        p1Hit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p1Hit.setForeground(new java.awt.Color(255, 51, 51));
        p1Hit.setText("Hits: ");

        p1Miss.setBackground(new java.awt.Color(255, 255, 255));
        p1Miss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p1Miss.setForeground(new java.awt.Color(255, 51, 51));
        p1Miss.setText("Miss: ");

        p1Acc.setBackground(new java.awt.Color(255, 255, 255));
        p1Acc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p1Acc.setForeground(new java.awt.Color(255, 51, 51));
        p1Acc.setText("Acc: ");

        p1Shots.setBackground(new java.awt.Color(255, 255, 255));
        p1Shots.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p1Shots.setForeground(new java.awt.Color(255, 51, 51));
        p1Shots.setText("Shots: ");

        p2Hit.setBackground(new java.awt.Color(255, 255, 255));
        p2Hit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p2Hit.setForeground(new java.awt.Color(255, 51, 51));
        p2Hit.setText("Hits: ");

        p2Miss.setBackground(new java.awt.Color(255, 255, 255));
        p2Miss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p2Miss.setForeground(new java.awt.Color(255, 51, 51));
        p2Miss.setText("Miss: ");

        p2Acc.setBackground(new java.awt.Color(255, 255, 255));
        p2Acc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p2Acc.setForeground(new java.awt.Color(255, 51, 51));
        p2Acc.setText("Acc: ");

        p2Shots.setBackground(new java.awt.Color(255, 255, 255));
        p2Shots.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p2Shots.setForeground(new java.awt.Color(255, 51, 51));
        p2Shots.setText("Shots: ");

        buttonAfslut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAfslut.setText("Done");
        buttonAfslut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAfslutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(winnerIsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(player1Label)
                                        .addComponent(p1Hit))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(p2Hit)
                                        .addComponent(p2Miss)
                                        .addComponent(p2Acc)
                                        .addComponent(p2Shots)
                                        .addComponent(player2Label))))
                            .addComponent(p1Miss)
                            .addComponent(p1Acc)
                            .addComponent(p1Shots)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(labelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(buttonAfslut)))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(winnerIsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label)
                    .addComponent(player2Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Hit)
                    .addComponent(p2Hit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Miss)
                    .addComponent(p2Miss))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Acc)
                    .addComponent(p2Acc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Shots)
                    .addComponent(p2Shots))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(buttonAfslut)
                .addGap(201, 201, 201))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAfslutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAfslutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonAfslutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAfslut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWinner;
    private javax.swing.JLabel p1Acc;
    private javax.swing.JLabel p1Hit;
    private javax.swing.JLabel p1Miss;
    private javax.swing.JLabel p1Shots;
    private javax.swing.JLabel p2Acc;
    private javax.swing.JLabel p2Hit;
    private javax.swing.JLabel p2Miss;
    private javax.swing.JLabel p2Shots;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player2Label;
    private javax.swing.JLabel winnerIsLabel;
    // End of variables declaration//GEN-END:variables
}
